=== UO289930/EscritorioVirtual/xml/rutas.dtd
<!ELEMENT rutas (ruta+)>
<!ELEMENT ruta (nombreRuta,tiempo,agencia,descripcionRuta,adecuado,lugarInicio,direccionInicio,coordenadasRuta,referencias,recomendacion,hitos)>
<!ATTLIST ruta tipo CDATA #REQUIRED>
<!ATTLIST ruta medio CDATA #REQUIRED>
<!ATTLIST ruta fechaInicio CDATA #IMPLIED>
<!ATTLIST ruta horaInicio CDATA #IMPLIED>
<!ELEMENT nombreRuta (#PCDATA)>
<!ELEMENT tiempo (#PCDATA)>
<!ELEMENT agencia (#PCDATA)>
<!ELEMENT descripcionRuta (#PCDATA)>
<!ELEMENT adecuado (#PCDATA)>
<!ELEMENT lugarInicio (#PCDATA)>
<!ELEMENT direccionInicio (#PCDATA)>
<!ELEMENT coordenadasRuta EMPTY>
<!ATTLIST coordenadasRuta longitud CDATA #REQUIRED>
<!ATTLIST coordenadasRuta latitud CDATA #REQUIRED>
<!ATTLIST coordenadasRuta altitud CDATA #REQUIRED>
<!ELEMENT referencias (referencia+)>
<!ELEMENT referencia (#PCDATA)>
<!ELEMENT recomendacion (#PCDATA)>
<!ELEMENT hitos (hito+)>
<!ELEMENT hito (nombreHito,descripcionHito,coordenadasHito,distanciaHitoAnterior,galeriaFotos,galeriaVideos?)>
<!ELEMENT nombreHito (#PCDATA)>
<!ELEMENT descripcionHito (#PCDATA)>
<!ELEMENT coordenadasHito EMPTY>
<!ATTLIST coordenadasHito longitud CDATA #REQUIRED>
<!ATTLIST coordenadasHito latitud CDATA #REQUIRED>
<!ATTLIST coordenadasHito altitud CDATA #REQUIRED>
<!ELEMENT distanciaHitoAnterior (#PCDATA)>
<!ATTLIST distanciaHitoAnterior unidades CDATA #REQUIRED>
<!ELEMENT galeriaFotos (foto+)>
<!ELEMENT foto (#PCDATA)>
<!ELEMENT galeriaVideos (video+)>
<!ELEMENT video (#PCDATA)>

=== UO289930/EscritorioVirtual/xml/rutas.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE rutas SYSTEM "rutas.dtd">
<rutas>
    <ruta nombreRuta="Ruta costera" tipo="Paisajística y gastronómica" medio="A pie">
        <tiempo>1 hora y media</tiempo>
        <agencia>Sin agencia</agencia>
        <descripcionRuta>Ruta costera al norte de Brunéi</descripcionRuta>
        <adecuado>Se puede ir con niños</adecuado>
        <lugarInicio>Pantai Seri Kenangan</lugarInicio>
        <direccionInicio>625, Jalan Kuala Tutong, Kampong Kuala Tutong, Brunei, Tutong TA3341, Brunéi</direccionInicio>
        <coordenadasRuta altitud="200" latitud="4.197431" longitud="114.043168">Inicio de la ruta</coordenadasRuta>
        <referencias>
            <referencia>
                Referencia 1: https://es.wikipedia.org/wiki/Geograf%C3%ADa_de_Brun%C3%A9i
            </referencia>
            <referencia>
                Referencia 2: https://es.wikiloc.com/rutas/a-pie/brunei
            </referencia>
            <referencia>
                Referencia 3: https://www.tripadvisor.es/Attraction_Review-g3135192-d447284-Reviews-Pantai_Seri_Kenangan-Tutong_Tutong_District.html
            </referencia>
        </referencias>
        <recomendacion>8</recomendacion>
        <hitos>
            <hito>
                <nombreHito>Kampong Penabai, Kuala Tutong Mosque</nombreHito>
                <descripcionHito>Mezquita</descripcionHito>
                <coordenadasHito altitud="0" longitud="4.790276596834284" latitud="114.61899278378765">Coordenadas Kampong Penabai</coordenadasHito>
                <distanciaHitoAnterior unidades="km">2.5</distanciaHitoAnterior>
                <galeriaFotos>
                    <foto>Foto: </foto>
                </galeriaFotos>
            </hito>
            <hito>
                <nombreHito>Istana Pantai</nombreHito>
                <descripcionHito>Castillo</descripcionHito>
                <coordenadasHito altitud="0" longitud="4.807468110763295" latitud="114.63856073741455">Coordenadas Istana Pantai</coordenadasHito>
                <distanciaHitoAnterior unidades="km">2.9</distanciaHitoAnterior>
                <galeriaFotos>
                    <foto>Foto: </foto>
                </galeriaFotos>
            </hito>
            <hito>
                <nombreHito>Fujiwara tofu shop</nombreHito>
                <descripcionHito>Gastronomía</descripcionHito>
                <coordenadasHito altitud="0" longitud="4.804738014211636" latitud="114.64495983293868">Coordenadas Istana Pantai</coordenadasHito>
                <distanciaHitoAnterior unidades="m">850</distanciaHitoAnterior>
                <galeriaFotos>
                    <foto>Foto: </foto>
                </galeriaFotos>
            </hito>
        </hitos>
    </ruta>
    <ruta nombreRuta="Ruta turística por centro de la capital de Brunéi, Bandar Ser Begawan" tipo="Arquitectura, monumentos, cultura" medio="A pie o transporte público">
        <tiempo>2 horas</tiempo>
        <agencia>Sin agencia</agencia>
        <descripcionRuta>Ruta a través del centro de la ciudad donde se podrán observar Jame' Asr Hassanil Bolkiah Mosque, la gran Mezquita del Sultán Omar Ali Saifuddin y por último la pequeña mezquita Balai Ibadat Kampong Saba.</descripcionRuta>
        <adecuado>Se puede ir con niños</adecuado>
        <lugarInicio>Jame' Asr Hassanil Bolkiah Mosque</lugarInicio>
        <direccionInicio>Simpang 127, Bandar Seri Begawan, Brunéi</direccionInicio>
        <coordenadasRuta altitud="50" latitud="4.89795093169754" longitud="114.92168727801855">Inicio de la ruta</coordenadasRuta>
        <referencias>
            <referencia>
                Referencia 1: ...
            </referencia>
            <referencia>
                Referencia 2: ...
            </referencia>
            <referencia>
                Referencia 3: ...
            </referencia>
        </referencias>
        <recomendacion>10</recomendacion>
        <hitos>
            <hito>
                <nombreHito>Masjid Jame' Asr Hassanil Bolkiah</nombreHito>
                <descripcionHito>Mezquita impresionante</descripcionHito>
                <coordenadasHito altitud="50" longitud="114.92168727801855" latitud="4.89795093169754">Coordenadas Masjid Jame' Asr Hassanil Bolkiah</coordenadasHito>
                <distanciaHitoAnterior unidades="km">0</distanciaHitoAnterior>
                <galeriaFotos>
                    <foto>Foto 1: </foto>
                </galeriaFotos>
            </hito>
            <hito>
                <nombreHito>Mezquita del Sultán Omar Ali Saifuddin</nombreHito>
                <descripcionHito>Mezquita principal</descripcionHito>
                <coordenadasHito altitud="50" longitud="114.93923818155807" latitud="4.889449185213048">Coordenadas Masjid Jame' Asr Hassanil Bolkiah</coordenadasHito>
                <distanciaHitoAnterior unidades="km">3.3</distanciaHitoAnterior>
                <galeriaFotos>
                    <foto>Foto 1: </foto>
                </galeriaFotos>
            </hito>
            <hito>
                <nombreHito>Balai Ibadat Kampong Saba</nombreHito>
                <descripcionHito>Mezquita en barrio pobre</descripcionHito>
                <coordenadasHito altitud="50" longitud="114.94441376981506" latitud="4.901602526126973">Coordenadas Masjid Jame' Asr Hassanil Bolkiah</coordenadasHito>
                <distanciaHitoAnterior unidades="km">5.5</distanciaHitoAnterior>
                <galeriaFotos>
                    <foto>Foto 1: </foto>
                </galeriaFotos>
            </hito>

        </hitos>
    </ruta>
    <ruta nombreRuta="Ruta forestal" tipo="Senderismo/Paisajística" medio="A pie">
        <tiempo>4 horas y 15 minutos</tiempo>
        <agencia>Sin agencia</agencia>
        <descripcionRuta>Ruta a través de diferentes bosques en Brunéi</descripcionRuta>
        <adecuado>Se puede ir con niños, aunque se pueden cansar</adecuado>
        <lugarInicio>Kargo Dam</lugarInicio>
        <direccionInicio>HHR3+5P5 Kargo Dam, Bang Bingol, Brunéi</direccionInicio>
        <coordenadasRuta altitud="200" latitud="4.5916878965355155" longitud="114.55407735158468">Inicio de la ruta</coordenadasRuta>
        <referencias>
            <referencia>
                Referencia 1: https://www.holidify.com/places/brunei/andulau-forest-reserve-sightseeing-1256132.html
            </referencia>
            <referencia>
                Referencia 2: https://en.wikipedia.org/wiki/Lalak_Lake
            </referencia>
            <referencia>
                Referencia 3: https://www.bruneitourism.com/bruneiplaces/luagan-lalak-recreation-park/
            </referencia>
        </referencias>
        <recomendacion>7</recomendacion>
        <hitos>
            <hito>
                <nombreHito>Kargo Dam</nombreHito>
                <descripcionHito></descripcionHito>
                <coordenadasHito altitud="200" latitud="4.5916878965355155" longitud="114.55407735158468">Coordenadas Kargo Dam</coordenadasHito>
                <distanciaHitoAnterior unidades="km">0</distanciaHitoAnterior>
                <galeriaFotos>
                    <foto>Foto: </foto>
                </galeriaFotos>
            </hito>
            <hito>
                <nombreHito>Taman Rekreasi Sg.Mau</nombreHito>
                <descripcionHito></descripcionHito>
                <coordenadasHito altitud="200" latitud="4.553491810192945" longitud="114.49034991825599">Coordenadas Taman Rekreasi Sg.Mau</coordenadasHito>
                <distanciaHitoAnterior unidades="km">12.2</distanciaHitoAnterior>
                <galeriaFotos>
                    <foto>Foto: </foto>
                </galeriaFotos>
            </hito>
            <hito>
                <nombreHito>Lalak Lake National Park</nombreHito>
                <descripcionHito></descripcionHito>
                <coordenadasHito altitud="200" latitud="4.515360715730574" longitud="114.47529147481819">Coordenadas Lalak Lake National Park</coordenadasHito>
                <distanciaHitoAnterior unidades="km">6.6</distanciaHitoAnterior>
                <galeriaFotos>
                    <foto>Foto: </foto>
                </galeriaFotos>
            </hito>
        </hitos>
    </ruta>
</rutas>
