=== UO289930/EscritorioVirtual/xml/rutas.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://www.uniovi.es" elementFormDefault="qualified" targetNamespace="http://www.uniovi.es" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="rutas">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="3" maxOccurs="unbounded" ref="ruta" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ruta">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombreRuta" minOccurs="1" maxOccurs="1" />
				<xs:element ref="tiempo" minOccurs="1" maxOccurs="1" />
				<xs:element ref="agencia" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="descripcionRuta" minOccurs="1" maxOccurs="1" />
				<xs:element ref="adecuado" minOccurs="1" maxOccurs="1" />
				<xs:element ref="lugarInicio" minOccurs="1" maxOccurs="1" />
				<xs:element ref="direccionInicio" minOccurs="1" maxOccurs="1" />
				<xs:element ref="coordenadasRuta" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="referencias" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="recomendacion" minOccurs="1" maxOccurs="1" />
				<xs:element ref="hitos" minOccurs="1" maxOccurs="1" />
			</xs:sequence>
			<xs:attribute name="tipo" type="xs:string" use="required" />
			<xs:attribute name="medio" type="xs:string" use="required" />
			<xs:attribute name="fechaHoraInicio" type="xs:dateTime" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="nombreRuta" type="xs:string" />
	<xs:element name="tiempo" type="xs:duration" />
	<xs:element name="agencia" type="xs:string" />
	<xs:element name="descripcionRuta" type="xs:string" />
	<xs:element name="adecuado" type="xs:string" />
	<xs:element name="lugarInicio" type="xs:string" />
	<xs:element name="direccionInicio" type="xs:string" />
	<xs:element name="coordenadasRuta">
		<xs:complexType>
			<xs:attribute name="longitud" type="xs:double" use="required" />
			<xs:attribute name="latitud" type="xs:double" use="required" />
			<xs:attribute name="altitud" type="xs:double" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="referencias">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="referencia" minOccurs="3" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="referencia" type="xs:string" />
	<xs:element name="recomendacion" >
		<xs:simpleType>
			<xs:restriction base="xs:positiveInteger">
				<xs:maxInclusive value="10" />
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="hitos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="3" maxOccurs="unbounded" ref="hito" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="hito">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombreHito" minOccurs="1" maxOccurs="1" />
				<xs:element ref="descripcionHito" minOccurs="1" maxOccurs="1" />
				<xs:element ref="coordenadasHito" minOccurs="1" maxOccurs="1" />
				<xs:element ref="distanciaHitoAnterior" minOccurs="1" maxOccurs="1" />
				<xs:element ref="galeriaFotos" minOccurs="1" maxOccurs="1" />
				<xs:element ref="galeriaVideos" minOccurs="0" maxOccurs="1" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="nombreHito" type="xs:string" />
	<xs:element name="descripcionHito" type="xs:string" />
	<xs:element name="coordenadasHito">
		<xs:complexType>
			<xs:attribute name="longitud" type="xs:double" use="required" />
			<xs:attribute name="latitud" type="xs:double" use="required" />
			<xs:attribute name="altitud" type="xs:double" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="distanciaHitoAnterior">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:double">
					<xs:attribute name="unidades" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="galeriaFotos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="5" ref="foto" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="foto" type="xs:string" />
	<xs:element name="galeriaVideos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="5" ref="video" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="video" type="xs:string" />
</xs:schema>

=== UO289930/EscritorioVirtual/xml/rutasEsquema.xml
<?xml version="1.0" encoding="UTF-8"?>
<rutas xmlns="http://www.uniovi.es" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.uniovi.es rutas.xsd">
    <ruta tipo="Paisajística y gastronómica" medio="A pie">
        <nombreRuta>Ruta costera</nombreRuta>
        <tiempo>PT1H30M</tiempo>
        <agencia>Sin agencia</agencia>
        <descripcionRuta>Ruta costera al norte de Brunéi</descripcionRuta>
        <adecuado>Se puede ir con niños</adecuado>
        <lugarInicio>Pantai Seri Kenangan</lugarInicio>
        <direccionInicio>625, Jalan Kuala Tutong, Kampong Kuala Tutong, Brunei, Tutong TA3341, Brunéi</direccionInicio>
        <coordenadasRuta altitud="10" latitud="4.776023" longitud="114.602583"/>
        <referencias>
            <referencia>https://es.wikipedia.org/wiki/Geograf%C3%ADa_de_Brun%C3%A9i</referencia>
            <referencia>https://es.wikiloc.com/rutas/a-pie/brunei</referencia>
            <referencia>https://www.tripadvisor.es/Attraction_Review-g3135192-d447284-Reviews-Pantai_Seri_Kenangan-Tutong_Tutong_District.html</referencia>
        </referencias>
        <recomendacion>8</recomendacion>
        <hitos>
            <hito>
                <nombreHito>Kampong Penabai, Kuala Tutong Mosque</nombreHito>
                <descripcionHito>Mezquita</descripcionHito>
                <coordenadasHito altitud="6" latitud="4.790276596834284" longitud="114.61899278378765"/>
                <distanciaHitoAnterior unidades="km">2.5</distanciaHitoAnterior>
                <galeriaFotos>
                    <foto>KualaTotongMosque.jpg</foto>
                    <foto>KualaTotongMosque2.jpg</foto>
                </galeriaFotos>
            </hito>
            <hito>
                <nombreHito>Istana Pantai</nombreHito>
                <descripcionHito>Castillo</descripcionHito>
                <coordenadasHito altitud="10" latitud="4.807468110763295" longitud="114.63856073741455"/>
                <distanciaHitoAnterior unidades="km">2.9</distanciaHitoAnterior>
                <galeriaFotos>
                    <foto>IstanaPantai.jpg</foto>
                    <foto>IstanaPantai2.jpg</foto>
                </galeriaFotos>
            </hito>
            <hito>
                <nombreHito>Fujiwara tofu shop</nombreHito>
                <descripcionHito>Gastronomía</descripcionHito>
                <coordenadasHito altitud="8" latitud="4.804738014211636" longitud="114.64495983293868"/>
                <distanciaHitoAnterior unidades="m">850</distanciaHitoAnterior>
                <galeriaFotos>
                    <foto>fujiwara.jpg</foto>
                </galeriaFotos>
            </hito>
        </hitos>
    </ruta>
    <ruta tipo="Arquitectura, monumentos, cultura" medio="A pie o transporte público">
        <nombreRuta>Ruta turística por centro de la capital de Brunéi, Bandar Ser Begawan</nombreRuta>
        <tiempo>PT2H</tiempo>
        <agencia>Sin agencia</agencia>
        <descripcionRuta>Ruta a través del centro de la ciudad donde se podrán observar Jame' Asr Hassanil Bolkiah Mosque, la gran Mezquita del Sultán Omar Ali Saifuddin y por último la pequeña mezquita Balai Ibadat Kampong Saba.</descripcionRuta>
        <adecuado>Se puede ir con niños</adecuado>
        <lugarInicio>Jame' Asr Hassanil Bolkiah Mosque</lugarInicio>
        <direccionInicio>Simpang 127, Bandar Seri Begawan, Brunéi</direccionInicio>
        <coordenadasRuta altitud="50" latitud="4.89795093169754" longitud="114.92168727801855"/>
        <referencias>
            <referencia>https://id.wikipedia.org/wiki/Jame%27_%27Asr_Hassanil_Bolkiah</referencia>
            <referencia>https://www.visitsoutheastasia.travel/top-sights/jame-asr-hassanil-bolkiah-mosque/</referencia>
            <referencia>https://www.flickr.com/photos/jlascar/18404307540</referencia>
        </referencias>
        <recomendacion>10</recomendacion>
        <hitos>
            <hito>
                <nombreHito>Masjid Jame' Asr Hassanil Bolkiah</nombreHito>
                <descripcionHito>Mezquita impresionante</descripcionHito>
                <coordenadasHito altitud="18" latitud="4.89795093169754" longitud="114.92168727801855"/>
                <distanciaHitoAnterior unidades="km">0</distanciaHitoAnterior>
                <galeriaFotos>
                    <foto>MasjidJame.jpg</foto>
                    <foto>MasjidJame2.jpg</foto>
                </galeriaFotos>
            </hito>
            <hito>
                <nombreHito>Mezquita del Sultán Omar Ali Saifuddin</nombreHito>
                <descripcionHito>Mezquita principal</descripcionHito>
                <coordenadasHito altitud="7" latitud="4.889449185213048" longitud="114.93923818155807"/>
                <distanciaHitoAnterior unidades="km">3.3</distanciaHitoAnterior>
                <galeriaFotos>
                    <foto>SultanOmarAli.jpg</foto>
                    <foto>SultanOmarAli2.jpg</foto>
                </galeriaFotos>
            </hito>
            <hito>
                <nombreHito>Balai Ibadat Kampong Saba</nombreHito>
                <descripcionHito>Mezquita en barrio pobre</descripcionHito>
                <coordenadasHito altitud="29" latitud="4.901602526126973" longitud="114.94441376981506"/>
                <distanciaHitoAnterior unidades="km">5.5</distanciaHitoAnterior>
                <galeriaFotos>
                    <foto>BalaiIbadat.jpg</foto>
                </galeriaFotos>
            </hito>
        </hitos>
    </ruta>
    <ruta tipo="Senderismo/Paisajística" medio="A pie">
        <nombreRuta>Ruta forestal</nombreRuta>
        <tiempo>PT4H15M</tiempo>
        <agencia>Sin agencia</agencia>
        <descripcionRuta>Ruta a través de diferentes bosques en Brunéi</descripcionRuta>
        <adecuado>Se puede ir con niños, aunque se pueden cansar</adecuado>
        <lugarInicio>Kargo Dam</lugarInicio>
        <direccionInicio>HHR3+5P5 Kargo Dam, Bang Bingol, Brunéi</direccionInicio>
        <coordenadasRuta altitud="200" latitud="4.5916878965355155" longitud="114.55407735158468"/>
        <referencias>
            <referencia>https://www.asonicassociates.com/portfolio-item/rehabilitation-of-kargo-dam-jaji-kaduna-state/</referencia>
            <referencia>https://en.wikipedia.org/wiki/Lalak_Lake</referencia>
            <referencia>https://www.bruneitourism.com/bruneiplaces/luagan-lalak-recreation-park/</referencia>
        </referencias>
        <recomendacion>7</recomendacion>
        <hitos>
            <hito>
                <nombreHito>Kargo Dam</nombreHito>
                <descripcionHito></descripcionHito>
                <coordenadasHito altitud="35" latitud="4.5916878965355155" longitud="114.55407735158468"/>
                <distanciaHitoAnterior unidades="km">0</distanciaHitoAnterior>
                <galeriaFotos>
                    <foto>KargoDam.jpg</foto>
                </galeriaFotos>
            </hito>
            <hito>
                <nombreHito>Taman Rekreasi Sg.Mau</nombreHito>
                <descripcionHito></descripcionHito>
                <coordenadasHito altitud="15" latitud="4.553491810192945" longitud="114.49034991825599"/>
                <distanciaHitoAnterior unidades="km">12.2</distanciaHitoAnterior>
                <galeriaFotos>
                    <foto>TamanRekreasi.jpg</foto>
                </galeriaFotos>
            </hito>
            <hito>
                <nombreHito>Lalak Lake National Park</nombreHito>
                <descripcionHito></descripcionHito>
                <coordenadasHito altitud="9" latitud="4.515360715730574" longitud="114.47529147481819"/>
                <distanciaHitoAnterior unidades="km">6.6</distanciaHitoAnterior>
                <galeriaFotos>
                    <foto>LalakLake.jpg</foto>
                    <foto>LalakLake2.jpg</foto>
                </galeriaFotos>
            </hito>
        </hitos>
    </ruta>
</rutas>
